services:
  php:
    user: '${USER_ID}:${GROUP_ID}'
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
    networks:
      - app_network

  nginx:
    build: ./docker/nginx
    ports:
     - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
     - php
    networks:
      - app_network           

  database:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app_network   

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8082:8080"
    networks:
      - app_network
      
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app_network          

networks:
  app_network:

volumes:
  database_data:  