version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony

  web:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  oracle-db:
    image: container-registry.oracle.com/database/free
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=MotDePasseFort
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: always

networks:
  symfony:
    driver: bridge

volumes:
  oracle_data:
    driver: local