services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Explicitly define the authenticator
    App\Security\ApiTokenAuthenticator:
        autowire: true
        autoconfigure: true
        public: false

    # Define the authentication handlers
    App\Security\AuthenticationSuccessHandler:
        arguments:
            $apiTokenSecret: '%env(APP_SECRET)%'  # Or use a dedicated secret

    App\Security\AuthenticationFailureHandler:
        autowire: true